In [ ]:
#imporiting pandas and numpy libraries
import numpy as np
import pandas as pd

In [ ]:
#loading the telecom 1 dataset
dt1 = pd.read_csv('Telcom_dataset.csv')
dt1
dt1.columns =['PRODUCT', 'VALUE', 'DATETIME', 'CELLONSITE', 'DWANUMBER', 'DWBNUMBER', 'COUNTRYA', 'COUNTTRYB' , 'CELLID', 'SITEID']
dt1.head()

  PRODUCT  VALUE               DATETIME  ... COUNTTRYB      CELLID      SITEID
0   Voice      0  2012-05-06 23:04:37.0  ...     19e2e  /TJNe+Mmtu  /TJNe+Mmtu
1     sms      0  2012-05-06 23:05:25.0  ...     19e2e  /+cKZKIp41  /+cKZKIp41
2     sms     25  2012-05-06 23:05:41.0  ...     19e2e  /u0FSD+ahi  /u0FSD+ahi
3   Voice     56  2012-05-06 23:05:42.0  ...     19e2e  +cNeJzsTp3  +cNeJzsTp3
4   Voice     14  2012-05-06 23:06:29.0  ...     19e2e  051KhYDCpv  051KhYDCpv

[5 rows x 10 columns]

In [ ]:
#loding telecom 2 dataset
dt2 = pd.read_csv('telcom_dataset2.csv')
dt2
dt2.columns =['PRODUCT', 'VALUE', 'DATETIME', 'CELLONSITE', 'DWANUMBER', 'DWBNUMBER', 'COUNTRYA', 'COUNTTRYB' , 'CELLID', 'SITEID']
dt2.head()

  PRODUCT  VALUE               DATETIME  ... COUNTTRYB      CELLID      SITEID
0     sms      0  2012-05-07 23:02:06.0  ...     19e2e  +854AcBQT2  +854AcBQT2
1   Voice      0  2012-05-07 23:03:44.0  ...     19e2e  +854AcBQT2  +854AcBQT2
2     sms      0  2012-05-07 23:04:06.0  ...     19e2e  +laSrk7g6q  +laSrk7g6q
3   Voice     37  2012-05-07 23:04:48.0  ...     19e2e  /xvRrCVKoQ  /xvRrCVKoQ
4     sms     25  2012-05-07 23:04:58.0  ...     19e2e  +bO+qkSonO  +bO+qkSonO

[5 rows x 10 columns]

In [ ]:
#loading telcom 3 dataset
dt3 = pd.read_csv('Telcom_dataset3.csv')
dt3
dt3.columns =['PRODUCT', 'VALUE', 'DATETIME', 'CELLONSITE', 'DWANUMBER', 'DWBNUMBER', 'COUNTRYA', 'COUNTTRYB' , 'CELLID', 'SITEID']
dt3.head()

  PRODUCT  VALUE               DATETIME  ... COUNTTRYB      CELLID      SITEID
0   Voice     61  2012-05-08 23:01:28.0  ...     19e2e  +38u2u/rfx  +38u2u/rfx
1     sms      0  2012-05-08 23:01:31.0  ...     19e2e  +Fs4mTvdKx  +Fs4mTvdKx
2   Voice     10  2012-05-08 23:02:59.0  ...     19e2e  +ZaaZozy/+  +ZaaZozy/+
3     sms      0  2012-05-08 23:03:04.0  ...     19e2e  +cNeJzsTp3  +cNeJzsTp3
4   Voice     22  2012-05-08 23:03:16.0  ...     19e2e  /eeMklgyJA  /eeMklgyJA

[5 rows x 10 columns]

In [ ]:
#loading cells geographric dataset
dt4 = pd.read_csv("cells_geo.csv")
dt4.columns = ["mycolumns"]

#splitting the columns in the data 
dt4 = dt4.mycolumns.str.split(";",expand=True)
dt4
#renaming columns of the dataset
dt4.columns = ['INDEX','VILLES', 'STATUS', 'LOCALISATION', 'DECOUPZONE' ,'ZONENAME', 'LONGITUDE', 'LATITUDE', 'REGION', 'AREA', 'CELLID' ,'SITEID']
dt4.head()

  INDEX   VILLES      STATUS  ... AREA      CELLID      SITEID
0     0   ADJAME  In Service  ...       fbb2e75af3  0bb492ef17
1     1   ADJAME  In Service  ...       1502501d78  0bb492ef17
2     2   ADJAME  In Service  ...       0c2e182a0c  0bb492ef17
3     3  ASSINIE  In Service  ...       69bdfc69fd  8a1e6ce31f
4     4  ASSINIE  In Service  ...       7a1029d2ab  8a1e6ce31f

[5 rows x 12 columns]

In [ ]:
#cleaning the first dataset
#checking for missing values
dt1.isnull()
 
#dropping duplicated values
dt1.duplicated()
dt1.drop_duplicates()

#droping rows if all cells are missing 
dt1_cleaned = dt1.dropna(how='all')
dt1_cleaned

#droping columns if all cells are missing 
dt1.dropna(axis=1, how='all')

dt1.dropna(thresh=10)

     PRODUCT  VALUE               DATETIME  ... COUNTTRYB      CELLID      SITEID
0      Voice      0  2012-05-06 23:04:37.0  ...     19e2e  /TJNe+Mmtu  /TJNe+Mmtu
1        sms      0  2012-05-06 23:05:25.0  ...     19e2e  /+cKZKIp41  /+cKZKIp41
2        sms     25  2012-05-06 23:05:41.0  ...     19e2e  /u0FSD+ahi  /u0FSD+ahi
3      Voice     56  2012-05-06 23:05:42.0  ...     19e2e  +cNeJzsTp3  +cNeJzsTp3
4      Voice     14  2012-05-06 23:06:29.0  ...     19e2e  051KhYDCpv  051KhYDCpv
...      ...    ...                    ...  ...       ...         ...         ...
4996     sms    100  2012-05-07 00:01:54.0  ...     OTHER  0c2371d9bc  1e751d08a4
4997   Voice      1  2012-05-07 00:01:54.0  ...     19e2e  5fb791cf56  65efe2bc62
4998   Voice      0  2012-05-07 00:01:54.0  ...     19e2e  7773627c12  9ef9616350
4999   Voice      0  2012-05-07 00:01:54.0  ...     19e2e  3f4af49d6c  969b8d0e39
5000   Voice      7  2012-05-07 00:01:54.0  ...     19e2e  6f4d9b77a5  ebfc58af70

[4285 rows x 10 columns]

In [ ]:
#cleaning the second dataset
#checking for missing values
dt2.isnull()

#checking and dropping duplicated values
dt2.duplicated() 
#dropping duplicated values
dt2.drop_duplicates()

#droping rows if all cells are missing 
#dt2_cleaned = dt1.dropna(how='all')
#dt2_cleaned

#droping columns if all cells are missing 
#dt2.dropna(axis=1, how='all')

dt2.dropna(thresh=10)

     PRODUCT  VALUE               DATETIME  ... COUNTTRYB      CELLID      SITEID
0        sms      0  2012-05-07 23:02:06.0  ...     19e2e  +854AcBQT2  +854AcBQT2
1      Voice      0  2012-05-07 23:03:44.0  ...     19e2e  +854AcBQT2  +854AcBQT2
2        sms      0  2012-05-07 23:04:06.0  ...     19e2e  +laSrk7g6q  +laSrk7g6q
3      Voice     37  2012-05-07 23:04:48.0  ...     19e2e  /xvRrCVKoQ  /xvRrCVKoQ
4        sms     25  2012-05-07 23:04:58.0  ...     19e2e  +bO+qkSonO  +bO+qkSonO
...      ...    ...                    ...  ...       ...         ...         ...
4995     sms     25  2012-05-08 00:01:53.0  ...     19e2e  0e8763bdaa  eefd93f0b4
4996     sms      0  2012-05-08 00:01:53.0  ...     19e2e  896459aace  b7d00e59e4
4997     sms     25  2012-05-08 00:01:53.0  ...     19e2e  7e90b35166  211015b14d
4998     sms      0  2012-05-08 00:01:53.0  ...     19e2e  fe70e431df  c7ea989264
5000   Voice      0  2012-05-08 00:01:53.0  ...     19e2e  8630058aca  b47a998a3e

[4325 rows x 10 columns]

In [ ]:
#cleaning the  telecom3 dataset
#checking for missing values
dt3.isnull()

#dropping duplicated values
dt3.duplicated()
dt3.drop_duplicates()

#droping rows if all cells are missing 
dt3_cleaned = dt1.dropna(how='all')
dt3_cleaned

#droping columns if all cells are missing 
dt3.dropna(axis=1, how='all')

dt3.dropna(thresh=10)

     PRODUCT  VALUE               DATETIME  ... COUNTTRYB      CELLID      SITEID
0      Voice     61  2012-05-08 23:01:28.0  ...     19e2e  +38u2u/rfx  +38u2u/rfx
1        sms      0  2012-05-08 23:01:31.0  ...     19e2e  +Fs4mTvdKx  +Fs4mTvdKx
2      Voice     10  2012-05-08 23:02:59.0  ...     19e2e  +ZaaZozy/+  +ZaaZozy/+
3        sms      0  2012-05-08 23:03:04.0  ...     19e2e  +cNeJzsTp3  +cNeJzsTp3
4      Voice     22  2012-05-08 23:03:16.0  ...     19e2e  /eeMklgyJA  /eeMklgyJA
...      ...    ...                    ...  ...       ...         ...         ...
4996   Voice      0  2012-05-09 00:01:43.0  ...     19e2e  2aa04dcab7  f7d63a29e5
4997   Voice     62  2012-05-09 00:01:43.0  ...     19e2e  7f1f2f889f  b4ddb9e93c
4998   Voice     32  2012-05-09 00:01:43.0  ...     19e2e  a4731e780e  d68260ef50
4999   Voice     30  2012-05-09 00:01:43.0  ...     19e2e  98ed726da2  b4130b54ab
5000   Voice     60  2012-05-09 00:01:43.0  ...     19e2e  1c11a2fcbb  6d70dae094

[4396 rows x 10 columns]

In [ ]:
#claening the cells geogrphical data
#checking for missing values
dt4.isnull()

#dropping duplicated values
dt4.drop_duplicates()
dt4_no_missing = dt4.dropna()
dt4_no_missing

#droping rows if all cells are missing 
dt4_cleaned = dt4.dropna(how='all')
dt4_cleaned

#droping columns if all cells are missing 
dt4.dropna(axis=1, how='all')

dt4.dropna(thresh=12)

     INDEX    VILLES      STATUS  ...          AREA      CELLID      SITEID
0        0    ADJAME  In Service  ...                fbb2e75af3  0bb492ef17
1        1    ADJAME  In Service  ...                1502501d78  0bb492ef17
2        2    ADJAME  In Service  ...                0c2e182a0c  0bb492ef17
3        3   ASSINIE  In Service  ...                69bdfc69fd  8a1e6ce31f
4        4   ASSINIE  In Service  ...                7a1029d2ab  8a1e6ce31f
...    ...       ...         ...  ...           ...         ...         ...
3969  3969  ZUENOULA  In Service  ...  CENTRE NORTH  1cfc2d7ab1  f91ed8d2e9
3970  3970  ZUENOULA  In Service  ...  CENTRE NORTH  3ae1708153  f91ed8d2e9
3971  3971  ZUENOULA  In Service  ...  CENTRE NORTH  cb71f8a29c  61bee9c70c
3972  3972  ZUENOULA  In Service  ...  CENTRE NORTH  d4a6a0b645  61bee9c70c
3973  3973  ZUENOULA  In Service  ...  CENTRE NORTH  f9f3e42589  61bee9c70c

[3974 rows x 12 columns]

In [ ]:
#merging the three telecom datasets
dt5 = pd.concat((dt1,dt2,dt3),axis =0,ignore_index=True)
dt5.head()

  PRODUCT  VALUE               DATETIME  ... COUNTTRYB      CELLID      SITEID
0   Voice      0  2012-05-06 23:04:37.0  ...     19e2e  /TJNe+Mmtu  /TJNe+Mmtu
1     sms      0  2012-05-06 23:05:25.0  ...     19e2e  /+cKZKIp41  /+cKZKIp41
2     sms     25  2012-05-06 23:05:41.0  ...     19e2e  /u0FSD+ahi  /u0FSD+ahi
3   Voice     56  2012-05-06 23:05:42.0  ...     19e2e  +cNeJzsTp3  +cNeJzsTp3
4   Voice     14  2012-05-06 23:06:29.0  ...     19e2e  051KhYDCpv  051KhYDCpv

[5 rows x 10 columns]

In [ ]:
#merging the mergerd telecom dataset with the cells geo
dt6 = dt5.merge(dt4, on='SITEID', how='inner')

#dropping columns COUNTRYA, COUNTRYB and CELL ON SITEas theywould not be usesful in analysis
dt6.drop(columns=['COUNTRYA','COUNTTRYB', 'CELLONSITE'],axis=1, inplace=True)
dt6.head()

  PRODUCT  VALUE  ...          AREA    CELLID_y
0     sms      0  ...  CENTRE NORTH  24ccdda3d5
1     sms      0  ...  CENTRE NORTH  ebfc58af70
2     sms      0  ...  CENTRE NORTH  ba8ce6e4ef
3     sms      0  ...  CENTRE NORTH  c2545171dc
4     sms      0  ...  CENTRE NORTH  f15bd5483f

[5 rows x 18 columns]

In [ ]:
#getting the 10 most used cities in the three days in descending order 
n= 10
dt6['VILLES'].value_counts()[:10]

YOPOUGON        8720
ABOBO           6266
COCODY          3814
ADJAME          2703
KOUMASSI        2333
MARCORY         2189
YAMOUSSOUKRO    2148
TREICHVILLE     2053
DALOA           1762
ATTECOUBE       1682
Name: VILLES, dtype: int64

In [ ]:
#most use city for the three days
dt6['VILLES'].value_counts()[:1]

YOPOUGON    8720
Name: VILLES, dtype: int64

In [ ]:
#converting the date time column from string to datetime objects

dt6['DATETIME'] = pd.to_datetime(dt6['DATETIME'])
dt6['DATETIME']

#to get the cities most used during business and home , we calculate the sum of datetime hours for every city
dt6.groupby([dt6['DATETIME'].dt.hour, 'VILLES'])['VALUE'].sum()

DATETIME  VILLES
0         ABENGOUROU         8709
          ABOBO            125921
          ABOISSO            1650
          ABOISSO COMOE       795
          ABONGOUA              3
                            ...
          ZATTA                 3
          ZIKISSO             968
          ZON-HOUNIEN         363
          ZOUKOUGBEU          714
          ZUENOULA           3846
Name: VALUE, Length: 400, dtype: int64

In [ ]:
#grouping product according to cities to determine which products were preferred between sms and voice
dt6.groupby(['PRODUCT','VILLES'])['VALUE'].count()

PRODUCT  VILLES
Voice    ABENGOUROU         96
         ABOBO            1966
         ABOISSO            42
         ABOISSO COMOE      12
         ABONGOUA            3
                          ...
sms      ZAIBO              15
         ZAROKO              3
         ZIKISSO            24
         ZOUKOUGBEU          6
         ZUENOULA           54
Name: VALUE, Length: 601, dtype: int64